 require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/layouts", type: :request do
  # Layout. As you add validations to Layout, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      Layout.create! valid_attributes
      get layouts_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      layout = Layout.create! valid_attributes
      get layout_url(layout)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_layout_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "render a successful response" do
      layout = Layout.create! valid_attributes
      get edit_layout_url(layout)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new Layout" do
        expect {
          post layouts_url, params: { layout: valid_attributes }
        }.to change(Layout, :count).by(1)
      end

      it "redirects to the created layout" do
        post layouts_url, params: { layout: valid_attributes }
        expect(response).to redirect_to(layout_url(Layout.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new Layout" do
        expect {
          post layouts_url, params: { layout: invalid_attributes }
        }.to change(Layout, :count).by(0)
      end

      it "renders a successful response (i.e. to display the 'new' template)" do
        post layouts_url, params: { layout: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested layout" do
        layout = Layout.create! valid_attributes
        patch layout_url(layout), params: { layout: new_attributes }
        layout.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the layout" do
        layout = Layout.create! valid_attributes
        patch layout_url(layout), params: { layout: new_attributes }
        layout.reload
        expect(response).to redirect_to(layout_url(layout))
      end
    end

    context "with invalid parameters" do
      it "renders a successful response (i.e. to display the 'edit' template)" do
        layout = Layout.create! valid_attributes
        patch layout_url(layout), params: { layout: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested layout" do
      layout = Layout.create! valid_attributes
      expect {
        delete layout_url(layout)
      }.to change(Layout, :count).by(-1)
    end

    it "redirects to the layouts list" do
      layout = Layout.create! valid_attributes
      delete layout_url(layout)
      expect(response).to redirect_to(layouts_url)
    end
  end
end
